export const generatedPluginFiles = Object.freeze([
  Object.freeze({
    destination: "plugins/hope/LICENSE",
    source: "LICENSE",
  }),
]);

export const staticPluginFiles = Object.freeze([
  "plugins/hope/.claude-plugin/plugin.json",
  "plugins/hope/.codex-plugin/plugin.json",
  "plugins/hope/assets/hope-protected-light.png",
  "plugins/hope/assets/hope-icon.png",
  "plugins/hope/assets/artifact-theme.mjs",
  "plugins/hope/assets/fonts/HopeCode.woff2",
  "plugins/hope/assets/fonts/HopeSansBold.woff2",
  "plugins/hope/assets/fonts/HopeSansMedium.woff2",
  "plugins/hope/assets/fonts/OFL-D2Coding.txt",
  "plugins/hope/assets/fonts/OFL-Gmarket.txt",
  "plugins/hope/assets/fonts/SOURCE.md",
  "plugins/hope/skills/align/SKILL.md",
  "plugins/hope/skills/align/agents/openai.yaml",
  "plugins/hope/skills/align/references/artifact.md",
  "plugins/hope/skills/align/references/design-directions.md",
  "plugins/hope/skills/align/scripts/align-input-v3.schema.json",
  "plugins/hope/skills/align/scripts/artifact.mjs",
  "plugins/hope/skills/align/scripts/cli.mjs",
  "plugins/hope/skills/align/scripts/design/tokens.mjs",
  "plugins/hope/skills/align/scripts/image.mjs",
  "plugins/hope/skills/align/scripts/render.mjs",
  "plugins/hope/skills/design/LICENSE.emil",
  "plugins/hope/skills/design/LICENSE.impeccable",
  "plugins/hope/skills/design/LICENSE.interface-design",
  "plugins/hope/skills/design/LICENSE.jakub",
  "plugins/hope/skills/design/SKILL.md",
  "plugins/hope/skills/design/agents/openai.yaml",
  "plugins/hope/skills/design/references/accessibility.md",
  "plugins/hope/skills/design/references/adaptation.md",
  "plugins/hope/skills/design/references/assets-and-performance.md",
  "plugins/hope/skills/design/references/continuity.md",
  "plugins/hope/skills/design/references/exploration.md",
  "plugins/hope/skills/design/references/interaction.md",
  "plugins/hope/skills/design/references/judgment.md",
  "plugins/hope/skills/design/references/motion.md",
  "plugins/hope/skills/design/references/prototypes.md",
  "plugins/hope/skills/design/references/sources.md",
  "plugins/hope/skills/design/references/verification.md",
  "plugins/hope/skills/design/references/visual-system.md",
  "plugins/hope/skills/diagram/LICENSE.diagram-design",
  "plugins/hope/skills/diagram/SKILL.md",
  "plugins/hope/skills/diagram/agents/openai.yaml",
  "plugins/hope/skills/diagram/references/chart-standard.md",
  "plugins/hope/skills/diagram/references/diagram-standard.md",
  "plugins/hope/skills/diff/SKILL.md",
  "plugins/hope/skills/diff/agents/openai.yaml",
  "plugins/hope/skills/diff/assets/hope-protected-light.png",
  "plugins/hope/skills/diff/references/analysis.md",
  "plugins/hope/skills/diff/references/runtime.md",
  "plugins/hope/skills/diff/references/teaching-aids.md",
  "plugins/hope/skills/diff/references/workflow.md",
  ...[
    "analysis-v4.schema.json",
    "artifact.mjs",
    "checkpoint-window-v2.schema.json",
    "checkpoint.mjs",
    "cli.mjs",
    "code-evidence.mjs",
    "constants.mjs",
    "context.mjs",
    "derive.mjs",
    "evidence-range.mjs",
    "github.mjs",
    "hash.mjs",
    "index.mjs",
    "redact.mjs",
    "render.mjs",
    "run.mjs",
    "structured-input.mjs",
    "target.mjs",
    "teaching-aids-v1.schema.json",
    "teaching-aids.mjs",
    "text.mjs",
    "transitions.mjs",
    "validate.mjs",
  ].map((name) => `plugins/hope/skills/diff/scripts/${name}`),
  "plugins/hope/skills/diff/scripts/design/tokens.mjs",
  "plugins/hope/skills/diff/scripts/locales/en-US/common.json",
  "plugins/hope/skills/diff/scripts/locales/en-US/diff.json",
  "plugins/hope/skills/diff/scripts/locales/index.mjs",
  "plugins/hope/skills/diff/scripts/locales/ko-KR/common.json",
  "plugins/hope/skills/diff/scripts/locales/ko-KR/diff.json",
  "plugins/hope/skills/sweep/SKILL.md",
  "plugins/hope/skills/sweep/agents/openai.yaml",
  "plugins/hope/skills/toxic-review/SKILL.md",
  "plugins/hope/skills/toxic-review/agents/openai.yaml",
  "plugins/hope/skills/write/SKILL.md",
  "plugins/hope/skills/write/agents/openai.yaml",
  "plugins/hope/skills/write/assets/hope-protected-light.png",
  "plugins/hope/skills/write/references/writing-standard.md",
]);

export const pluginPackageFiles = Object.freeze([
  ...generatedPluginFiles.map((entry) => entry.destination),
  ...staticPluginFiles,
].map((path) => path.replace(/^plugins\/hope\//u, "")).sort());
